site_name: Onslaught

nav:
  - Introduction: index.md
  - ChangeLog: changelog.md
  - Commands: commands.md
  - Invasion:
      - Templates: invasion/template.md
  - Mob:
      - Templates: mob/template.md
      - Custom AI: mob/customai.md

theme:
  name: readthedocs

markdown_extensions:
  - admonition
  - attr_list

extra_css: [custom.css]